version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  manylinux2014-aarch64:
    parameters:
      cibw_build:
        type: string
        default: "cp37-*"
  
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

      - run:
          name: Install dependencies
          command: |
             export md5sum $(which python) > ~/python_cache_key.md5
             export md5sum lib/Pipfile >> ~/python_cache_key.md5
             export md5sum lib/test-requirements.txt >> ~/python_cache_key.md5
             export md5sum lib/test-requirements-with-tensorflow.txt >> ~/python_cache_key.md5
             export date +%F >> ~/python_cache_key.md5
             export md5sum frontend/yarn.lock > ~/yarn.lock.md5
             apt update
             apt-get install -y make
             apt-get install -y graphviz
             apt-get install -y unixodbc-dev
             apt-get install -y libgvc6
             python -m venv venv
             source venv/bin/activate
             pip install --upgrade pip
             make setup
             make pipenv-install
             make setup
             make pipenv-install
             apt-get install -y gnupg
             echo "deb http://ppa.launchpad.net/maarten-fonville/protobuf/ubuntu trusty main" | ${SUDO} tee /etc/apt/sources.list.d/protobuf.list
             apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4DEA8909DC6A13A3
             apt-get install -y protobuf-compiler
             make protobuf
             make develop
             make jslint
             make pylint
             scripts/mypy --report         
      - run:
          name: Run python tests
          command: |
             make pycoverage        
workflows:
  version: 2.1
  main:
    jobs:
      - manylinux2014-aarch64:
          matrix:
            parameters:
              cibw_build:
                - "cp37*"
